### ISSUE TITLE
formatParamsDesc not sanitizing input

### ISSUE THREAD

**Issue by kleinwareio** [skinny85/specnaz#16]
Specnaz Version 1.5.2

It looks like `Conversions.java`, line 344 needs to sanitize the replacement string.

Specifically, it looks like a `$` in the replacement string is a problem

```kotlin
class FormatTests: SpecnazKotlinParamsJUnitPlatform("Format", {
    it.describes("failure %1") { _: Any ->
        it.should("not fail") {
        }
    }.provided(object {}, "Nope$")
})
```

**Comment by skinny85** [comment]
Hey @kleinwareio,

thanks for reporting! Confirming I was able to reproduce the issue.

The problem is indeed in [this line](https://github.com/skinny85/specnaz/blob/28ddbbe713678a35226021024d1eb7892e6daf16/src/main/specnaz/src/main/java/org/specnaz/params/impl/Conversions.java#L344), as you've correctly found already. Apparently, the `replaceAll()` method treats some characters in the string being inserted in a special way, which I didn't realize before. From the [JavaDocs of the method](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#replaceAll(java.lang.String)):

>  Note that backslashes (`\\`) and dollar signs (`$`) in the replacement string may cause the results to be different than if it were being treated as a literal replacement string. Dollar signs may be treated as references to captured subsequences as described above, and backslashes are used to escape literal characters in the replacement string. 

Apparently, the way to fix it is to use a different method:

>  Use `Matcher.quoteReplacement(java.lang.String)` to suppress the special meaning of these characters, if desired.

I'll prepare a PR fixing this.

**Comment by skinny85** [comment]
Ok, the bug has been fixed, now I need to cut a release.

**Comment by skinny85** [comment]
OK, the release `1.5.3` with this bugfix has been cut, and is [available on Maven Central](https://search.maven.org/artifact/org.specnaz/specnaz/1.5.3/jar).

I will import it internally soon™.
